version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app
permissions:
  - object: /
    pattern: '**'
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/install
      timeout: 7200
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start
      timeout: 7200
      runas: ec2-user
