name: ci

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  api:
    runs-on: ubuntu-latest

    env:
      MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}
      SECRET: ${{ secrets.SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --manifest-path ./api/Cargo.toml --verbose
      - name: Run tests
        run: cargo test --manifest-path ./api/Cargo.toml --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: [api]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name save-it \
            --deployment-group-name save-it-deploy \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
