name: Rust

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --manifest-path ./api/Cargo.toml --verbose
      - name: Run tests
        run: cargo test --manifest-path ./api/Cargo.toml --verbose
